info:
  namespace: omc_contest
items:
  contest_shell:
    display_name: <lang:itemsadder.omc_contest.contest_shell.name>
    resource:
      material: PAPER
      model_path: items/shell
    lore:
      - <lang:itemsadder.omc_contest.contest_shell.lore.0>
      - <lang:itemsadder.omc_contest.contest_shell.lore.1>
      - <lang:itemsadder.omc_contest.contest_shell.lore.2>
      - ""
      - <lang:itemsadder.omc_contest.contest_shell.lore.4>