info:
  namespace: omc_contest
items:
  contest_shell:
    name: "<aqua>Coquillage de Contest"
    material: NAUTILUS_SHELL
    graphics:
      model: items/shell
    lore:
      - "<gray><italic>un mystérieux coquillage..."
      - "<gray>Déposez le lors d'un Contest"
      - "<gray>Utile si vous voulez faire gagner votre équipe"
      - ""
      - "<dark_purple><bold>EPIC ITEM"