changelog:
  categories:
    - title: "🎮 Mise à jour de Minecraft !"
      labels:
        - "🎮 Game Update"
    - title: Nouvelles Fonctionnalités
      labels:
        - ":package:  Features"
    - title: Corrections de Bugs & Optimisations
      labels:
        - "⚡Optimisation"
        - ":sparkles: Fixes"
    - title: Changements & Améliorations
      labels:
        - ":arrows_counterclockwise: Changement"
        - "🆙 Amélioration"
    - title: Autre
      labels:
        - "*"
