changelog:
  categories:
    - titre: Mises à Jour de Minecraft !
      labels:
        - "🎮 Game Update"
    - title: Nouvelles Fonctionnalités
      labels:
        - "🆙 Amélioration"
        - ":arrows_counterclockwise: Changement"
        - ":package:  Features"
    - title: Bugs et Optimisations
      labels:
        - "⚡Optimisation"
        - ":sparkles: Fixes"
    - title: Autre
      labels:
        - "*"
