info:
  namespace: omc_icons
font_images:
  openmc:
    permission: server-icon
    show_in_gui: false
    path: "font/openmc.png"
    scale_ratio: 60
    y_position: 60
  dream_openmc:
    permission: server-icon
    show_in_gui: false
    path: "font/dream_openmc.png"
    scale_ratio: 80
    y_position: 60
  openmc_logo:
    permission: openmc_logo
    show_in_gui: false
    path: "font/openmc_logo.png"
    scale_ratio: 80
    y_position: 30
  aywenito:
    permission: aywenito
    show_in_gui: true
    path: "font/aywenito.png"
    scale_ratio: 12
    y_position: 9
  bits:
    permission: bits
    show_in_gui: true
    path: "font/bits.png"
    scale_ratio: 12
    y_position: 9
  candy_red:
    permission: candy_red
    show_in_gui: true
    path: "font/candy/candy_red.png"
    scale_ratio: 12
    y_position: 9
  candy_yellow:
    permission: candy_yellow
    show_in_gui: true
    path: "font/candy/candy_yellow.png"
    scale_ratio: 12
    y_position: 9
  candy_green:
    permission: candy_green
    show_in_gui: true
    path: "font/candy/candy_green.png"
    scale_ratio: 12
    y_position: 9
  candy_blue:
    permission: candy_blue
    show_in_gui: true
    path: "font/candy/candy_blue.png"
    scale_ratio: 12
    y_position: 9
  candy_brown:
    permission: candy_brown
    show_in_gui: true
    path: "font/candy/candy_brown.png"
    scale_ratio: 12
    y_position: 9