info:
  namespace: omc_icons
items:
  openmc-armor-icon:
    display_name: <lang:itemsadder.omc_icons.openmc-armor-icon.name>
    resource:
      material: PAPER
      generate: true
      textures: 
        - openmc-armor-icon