info:
  namespace: omc_homes
items:
  omc_homes_icon_axenq:
    enabled: true
    name: Pourquoi faire ?
    graphics:
      texture: icons/axenq
  omc_homes_icon_bank:
    enabled: true
    name: Pourquoi faire ?
    graphics:
      texture: icons/bank
  omc_homes_icon_chateau:
    enabled: true
    name: Pourquoi faire ?
    graphics:
      texture: icons/chateau
  omc_homes_icon_chest:
    enabled: true
    name: Pourquoi faire ?
    graphics:
      texture: icons/chest
  omc_homes_icon_grass:
    enabled: true
    name: Pourquoi faire ?
    graphics:
      texture: icons/grass
  omc_homes_icon_maison:
    enabled: true
    name: Pourquoi faire ?
    graphics:
      texture: icons/maison
  omc_homes_icon_sandblock:
    enabled: true
    name: Pourquoi faire ?
    graphics:
      texture: icons/sandblock
  omc_homes_icon_shop:
    enabled: true
    name: Pourquoi faire ?
    graphics:
      texture: icons/shop
  omc_homes_icon_xernas:
    enabled: true
    name: Pourquoi faire ?
    graphics:
      texture: icons/xernas
  omc_homes_icon_zombie:
    enabled: true
    name: Pourquoi faire ?
    graphics:
      texture: icons/zombie
  omc_homes_icon_upgrade:
    enabled: true
    name: Pourquoi faire ?
    graphics:
      texture: icons/upgrade
  omc_homes_icon_information:
    enabled: true
    name: Pourquoi faire ?
    graphics:
      texture: icons/information
  omc_homes_icon_bin:
    enabled: true
    name: Pourquoi faire ?
    graphics:
      texture: icons/bin
  omc_homes_icon_bin_red:
    enabled: true
    name: Pourquoi faire ?
    graphics:
      texture: icons/bin_red
  omc_homes_invisible:
    enabled: true
    name: Pourquoi faire ?
    graphics:
      texture: items/invisible
font_images:
  bin:
      permission: 0
      show_in_gui: true
      path: "icons/bin"
      scale_ratio: 9
      y_position: 8
  bin_red:
      permission: 0
      show_in_gui: true
      path: "icons/bin_red"
      scale_ratio: 9
      y_position: 8