#####
# Database
#####
database:
  url: "jdbc:mysql://host:port/openmc"
  username: ""
  password: ""

features:
  analytics: true
  transactions: true

chat:
  # {prefix}, {suffix}, {name}, {message}
  message: "&r{prefix} {name}&8: &f{message}"

bot-discord:
  bot-token: "TOKEN_BOT_DISCORD"
  guild-id: "ID_SERVEUR_DISCORD"

#####
# Paramètres pour un environnement de production
#####
homepage: "https://openmc.fr/"
discord: "https://aywen.fr/discord/"
blog: "https://blog.openmc.fr/"
wiki: "https://wiki.openmc.fr/"
