#####
# Database
#####
database:
  url: "jdbc:mysql://hz0hv.h.filess.io:3306/crgdtest_broughtran"
  username: "crgdtest_broughtran"
  password: "+srhuttsvh+&sZY2j$U%<^fCyqw)8]"

features:
  analytics: true
  transactions: true

#####
# Paramètres pour un environnement de production
#####
homepage: "https://openmc.fr/"
discord: "https://discord.gg/aywen/"
blog: "https://blog.openmc.fr/"