info:
  namespace: omc_shops
items:
  company_box:
    display_name: <lang:itemsadder.omc_shops.company_box.name>
    resource:
      material: PAPER
      generate: true
      textures:
        - company_box