info:
  namespace: omc_quests
items:
  quests_right_arrow:
    display_name: <lang:itemsadder.omc_quests.quests_right_arrow.name>
    resource:
      material: PAPER
      generate: true
      textures: 
        - right_arrow
  quests_left_arrow:
    display_name: <lang:itemsadder.omc_quests.quests_left_arrow.name>
    resource:
      material: PAPER
      generate: true
      textures: 
        - left_arrow