info:
  namespace: omc_quests
items:
  quests_right_arrow:
    name: Pourquoi faire ?
    graphics:
      texture: right_arrow
  quests_left_arrow:
    name: Pourquoi faire ?
    graphics:
      texture: left_arrow
