info:
  namespace: omc_menus
items:
  accept_btn:
    name: accept
    graphics:
      texture: accept_btn
  refuse_btn:
    name: refuse
    graphics:
      texture: refuse_btn
  1_btn:
    name: 1
    graphics:
      texture: 1_btn
  64_btn:
    name: 10
    graphics:
      texture: 64_btn
  plus_btn:
    name: plus
    graphics:
      texture: plus_btn
  minus_btn:
    name: plus
    graphics:
      texture: minus_btn
  mailbox_accept_btn:
    name: accept
    graphics:
      texture: "items/mailbox/accept_btn"
  mailbox_refuse_btn:
    name: refuse
    graphics:
      texture: "items/mailbox/refuse_btn"
  mailbox_cancel_btn:
    name: accept
    graphics:
      texture: "items/mailbox/cancel_btn"
  mailbox_arrow_left:
      name: arrow left
      graphics:
        texture: "items/mailbox/arrow_left"
  mailbox_arrow_right:
      name: arrow right
      graphics:
        texture: "items/mailbox/arrow_right"
  mailbox_send:
    name: send
    graphics:
      texture: "items/mailbox/paper_plane"
  mailbox_hourglass:
      name: hourglass
      graphics:
    
          texture: "items/mailbox/hourglass"
