name: Build & Test

on:
  pull_request:
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "LICENSE"
      - "README.md"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
  push:
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "LICENSE"
      - "README.md"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up GraalVM JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: graalvm
          java-version: 21
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Tests with Gradle
        run: ./gradlew test --no-daemon --stacktrace

      - name: Report test results
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Gradle Tests
          path: build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: true

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up GraalVM JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: graalvm
          java-version: 21
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with snapshot version
        env:
          SNAPSHOT: true
          GITHUB_SHA: ${{ github.sha }}
        run: ./gradlew jar --no-daemon --stacktrace

      - name: Upload Plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: OpenMC-${{ github.sha }}
          path: builds/