name: Milestone Checks

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-milestone:
    name: Does PR have a milestone
    runs-on: ubuntu-latest
    steps:
      - name: Verify that PR has been assigned a milestone
        run: |
          if [ "${{ github.event.pull_request.milestone }}" == "" ]; then
            echo "❌ PR has not been assigned a milestone."
            exit 1
          fi
  check-target:
    name: Is target branch the milestone branch
    runs-on: ubuntu-latest
    steps:
      - name: Verify target branch is correct milestone
        run: |
          MILESTONE_TITLE="${{ github.event.pull_request.milestone.title }}"
          BRANCH_NAME=milestone-$(echo "$MILESTONE_TITLE" | tr ' ' '-' | tr -cd '[:alnum:]-')
          if [ "${{ github.event.pull_request.base.ref }}" != "$BRANCH_NAME" ]; then
            echo "❌ Target branch is not Milestone branch. It should be $BRANCH_NAME" exit 1
            exit 1
          fi
      - name: Verify target branch is correct milestone
        run: |
          MILESTONE_TITLE="${{ github.event.pull_request.milestone.title }}"
          BRANCH_NAME=milestone-$(echo "$MILESTONE_TITLE" | tr ' ' '-' | tr -cd '[:alnum:]-')
          if [ "${{ github.event.pull_request.base.ref }}" == "$BRANCH_NAME" ]; then
            echo "✅ Target branch is correct milestone branch"
          else
            echo "❌ Target branch is not Milestone branch. It should be $BRANCH_NAME"
            exit 1
          fi

