name: Build DEV Jars

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  push:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build_dev_jars:
    name: Build DEV jars
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew shadowJar -DPLUGIN_VERSION=2.0.0 -DSNAPSHOT=true
        env:
          GITHUB_SHA: ${{ github.sha }}

      - name: Upload Plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: OpenMC-${{ github.sha }}
          path: builds/OpenMC-*.jar
          
