name: Handle closing a milestone

on:
  milestone:
    types: [closed]

jobs:
  build-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release tag
        run: |
          TAG_NAME="${{ github.event.milestone.title }}"
          git tag -a $TAG_NAME -m "Release ${{ github.event.milestone.title }}"
          git push origin $TAG_NAME
          
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Create release folder
        run: mkdir -p release && mv builds/OpenMC.jar release/OpenMC-${{ github.event.milestone.title }}.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenMC-${{ github.event.milestone.title }}
          path: release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.milestone.title }} 
          name: Release ${{ github.event.milestone.title }} 
          body: |
            # Release ${{ github.event.milestone.title }} 
            
            ${{ github.event.milestone.description }}
            
            This release was automatically created when milestone "${{ github.event.milestone.title }}" was closed.
          files: release/OpenMC-${{ github.event.milestone.title }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
