name: Handle closing a milestone

on:
  milestone:
    types: [closed]

jobs:
  build-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: |
          ./gradlew shadowJar
          cp ./builds/OpenMC.jar ./builds/OpenMC-$TAG.jar
        env:
          TAG: ${{ github.event.milestone.title }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenMC-${{ github.event.milestone.title }}
          path: builds/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.milestone.title }} 
          name: Release milestone ${{ github.event.milestone.title }} 
          generate_release_notes: true
          fail_on_unmatched_files: true
          make_latest: true
          body: |
            # Release milestone ${{ github.event.milestone.title }}
            
            ${{ github.event.milestone.description }}
            
            This release was automatically created when milestone "${{ github.event.milestone.title }}" was closed.
          files: builds/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to server
        uses: rexlmanu/pterodactyl-upload-action@v2.4
        with:
          panel-host: ${{ secrets.PANEL_HOST }}
          api-key: ${{ secrets.API_KEY }}
          server-id: ${{ secrets.SERVER_ID }}
          source: builds/OpenMC.jar
          target: "./plugins/OpenMC.jar"
          restart: true
