name: Pull Request Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build-snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Set SNAPSHOT=true for versioning
        run: echo "SNAPSHOT=true" >> $GITHUB_ENV

      - name: Build with snapshot version
        env:
          SNAPSHOT: true
          GITHUB_SHA: ${{ github.sha }}
        run: ./gradlew shadowJar

      - name: Show final jar file
        run: ls -lh builds/
