name: Release Stable Jar

on:
  milestone:
    types: [closed]

permissions:
  contents: write

jobs:
  build:
    if: startsWith(github.event.milestone.title, '2.') # Evite =~ qui n'existe pas ici
    runs-on: ubuntu-latest

    env:
      SNAPSHOT: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean shadowJar

      - name: Create Release directory
        run: mkdir -p release && mv builds/OpenMC.jar release/OpenMC-${{ github.event.milestone.title }}.jar

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenMC-${{ github.event.milestone.title }}
          path: release/OpenMC-${{ github.event.milestone.title }}.jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: OpenMC ${{ github.event.milestone.title }}
          tag_name: ${{ github.event.milestone.title }}
          files: release/OpenMC-${{ github.event.milestone.title }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
